server:
  port: 9200

spring:
  application:
    name: shop-gateway
  # 开启基于注册中心的路由表。gateway可以通过开启以下配置来打开根据服务的serviceId来匹配路由,默认是大写:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          #开启小写验证，默认feign根据服务名查找都是用的全大写
          lowerCaseServiceId: true
      routes:
        - id: SYSTEM
          uri: lb://SYSTEM
          predicates:
            - Path=/SYSTEM/**
          filters:
            - StripPrefix=1
        - id: service-feign
          uri: lb://FEIGN
          predicates:
            - Path=/service-feign/**
          filters:
            - StripPrefix=1

  security:
    user:
      name: admin
      password: 123456
#eureka:
#  instance:
#    preferIpAddress: true
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#  client:
#    service-url:
#      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@39.106.110.85:9100/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@106.52.28.89:9100/eureka/

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    hostname: 127.0.0.1 #服务注册中心IP地址
    lease-expiration-duration-in-seconds: 1 # 表示eureka server至上一次收到client的心跳之后，等待下一次心跳的超时时间，在这个时间内若没收到下一次心跳，则将移除该instance。 默认为90秒
    lease-renewal-interval-in-seconds: 1 # 表示eureka client发送心跳给server端的频率。如果在leaseExpirationDurationInSeconds后，server端没有收到client的心跳，则将摘除该instance 默认30秒
  client:
    register-with-eureka: true
    fetch-registry: true
    #    healthcheck:
    #      enabled: true
    serviceUrl:
      #      集群版
      #      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@eureka.com:9100/eureka/,http://${spring.security.user.name}:${spring.security.user.password}@eureka1.com:9101/eureka/,,http://${spring.security.user.name}:${spring.security.user.password}@eureka2.com:9102/eureka/
      #defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:9100/eureka/
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:9100/eureka/


#开启基于注册中心的路由表。gateway可以通过开启以下配置来打开根据服务的serviceId来匹配路由,默认是大写:
#cloud:
#  gateway:
#    discovery:
#      locator:
#        enabled: true